#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xEC94D18F7F05997E (jr@jriddell.org)
#
Name     : drkonqi
Version  : 5.15.1
Release  : 13
URL      : https://download.kde.org/stable/plasma/5.15.1/drkonqi-5.15.1.tar.xz
Source0  : https://download.kde.org/stable/plasma/5.15.1/drkonqi-5.15.1.tar.xz
Source99 : https://download.kde.org/stable/plasma/5.15.1/drkonqi-5.15.1.tar.xz.sig
Summary  : The KDE crash handler
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: drkonqi-data = %{version}-%{release}
Requires: drkonqi-license = %{version}-%{release}
Requires: drkonqi-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : kidletime-dev
BuildRequires : kxmlrpcclient-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : zlib-dev

%description
This is a unit test for the BacktraceInfo class, which is used in drkonqi
to rate the usefulness of a backtrace.

%package data
Summary: data components for the drkonqi package.
Group: Data

%description data
data components for the drkonqi package.


%package license
Summary: license components for the drkonqi package.
Group: Default

%description license
license components for the drkonqi package.


%package locales
Summary: locales components for the drkonqi package.
Group: Default

%description locales
locales components for the drkonqi package.


%prep
%setup -q -n drkonqi-5.15.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550586528
mkdir -p clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1550586528
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/drkonqi
cp COPYING %{buildroot}/usr/share/package-licenses/drkonqi/COPYING
cp COPYING.LIB %{buildroot}/usr/share/package-licenses/drkonqi/COPYING.LIB
pushd clr-build
%make_install
popd
%find_lang drkonqi5

%files
%defattr(-,root,root,-)
/usr/lib64/libexec/drkonqi

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.drkonqi.desktop
/usr/share/drkonqi/debuggers/external.mac/lldbrc
/usr/share/drkonqi/debuggers/external/gdbrc
/usr/share/drkonqi/debuggers/external/kdbgrc
/usr/share/drkonqi/debuggers/external/lldbrc
/usr/share/drkonqi/debuggers/internal/dbxrc
/usr/share/drkonqi/debuggers/internal/gdbrc
/usr/share/drkonqi/debuggers/internal/kdbgwinrc
/usr/share/drkonqi/debuggers/internal/lldbrc
/usr/share/drkonqi/mappings
/usr/share/xdg/drkonqi.categories

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/drkonqi/COPYING
/usr/share/package-licenses/drkonqi/COPYING.LIB

%files locales -f drkonqi5.lang
%defattr(-,root,root,-)

